pipeline{
  agent any  
  stages {
   stage("Opening"){
         steps{
            //Welcome message
            script{
               sh "echo 'Welcome to Jenkins'"
}
}
}

   stage("Workspace_cleanup"){
        //Cleaning WorkSpace
        steps{
            step([$class: 'WsCleanup'])
}
}

   stage("Repo_clone"){
       //Clone repo from GitHub
      steps {
         checkout ([$class: 'GitSCM', branches: [[name: '^(?!.*master).*$']], userRemoteConfigs: [[credentialsId: 'instance_id', url: 'git@github.com:Vikas-Tamboli/master1.git']]])

}
}

   stage("terraform_init"){
     //terraform init
     steps{
      script{
       sh '''
            cd /root/github/master1/infra
            bash plugins.sh
            cd -
       '''
}
}
}

   
   stage("static_analysis"){
     //static analysis
      steps{
       script{
       sh '''
            cd /root/github/master1/infra
            terraform validate 
            cd -
       '''
}
}
}   

   
}
}
